language: node_js
node_js:
- '0.10'
install:
- npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: ThYyYBFL0AZ7VGFK2N8lwerPxJRbu8l1NPfMpd6rPSKQW6srvzI7pk8EUYK2TAHqxPi/TiKjqjq3BhVMcR9U72Lk4XNipmic6YY3qjyE4UOibevq+TlTTS1mZrSTckVk/Zgp20Ld1L3FWZ3FKE+9evbxTzIEqKl0SwGUkG3Li6qIrO7IZvfWG8zTl2ydZLi76A/prmN4PdFGEYDwh9fVGhnJkQbGVaF+9zaqfv9Bd8vjb0qC0aJRUVYQ1vwYKAtSa2cIBeR4l88tjI4zL9cAhWbfzxaqhbQwPB5/rvyMsvY+50Zrwx5OM/K4YXP8jemjnDkRw3QSpHuZzjY6UXKduNs1KIA4jVKJI9+m7dAVXSIZo3cnXqX18C1UuhTq9FnymrQFhQS/xenX4sXW82mMSyLgihkJYSf4m9Tf6QOgeadPRXkfiBBRSIuwpTm1y/TvrLBEPj5WDoER5uauk99bUEpKz5FmN2EDWDuTaqTGEDQSUOFpjEJ7BMj7DEYSO7YGU378w8dE/a0brMT40reabz7r58dtNulPr6+Gmr2yTfWib2yUCwwWc8OFe4r+49snDnO8PSiccJB9midjbu/0UohOyIcfhGGnRB+Glklwn/h5M/YY1tOD4y1/hxiIKuam29C67DFneo1o9vAwBhjAd3cNhVcGtN+qcJr4Lc7j+ac=
  app: dove-mail
  on:
    repo: niwasmala/dove-mail
