language: node_js
node_js:
- '0.10'
install:
- npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: NvwKIRaAEGNJJQV2sUkfXczR5/Wnh9in8nYt5Ns+Dl4A00xEmpE+/vt4p/YQ6eDM/1NfrV8Yu4vbyXXIEUZPqG4kOXM/Ix6OUQ3eMMr5o8+I7C2YtQTKuzrARM1+vYMD4ZtVMQ8gOdRj7t42uWV6ZnFNaFgsnoq/W8IM15NLQcclqN0tEg/r9DKT/ReUKsF/afb4Iqsr7GH0dIffPjYf2azphWkzfPnLhjgM8ljnU6FJtF2lIlAqrP1hOirxzY/Qunoo9K4lhtt2NuO5MBHhr52BuGCSIeeYu3jLi4HShxGz6v7gocRUKAnMD8J/B3cBAIphmEW2ofGQpJUPvTzt2ggxdis9hN03/In1HNfc4MzwaFkD5PSO/ekNBbpJyQ6/as7B5PA3Ohcy0+DodOUSo3ubdU138y3DYAhwW9Vz1PKaMLEwNdxIhwCt8D0rq/decY1yIC4lDcy57DVEP9y2Ul5C+HzJ0114rtOKeiG4uXJTv5I3m3Q33Vk47KG8MDvKS1m4nJPZJpCyQMUlrX090UKAbN4JPeqM6ZdAdfdSFh3XKZKHqO6GWWFE+al+VQYcf8CRpNRNKz0wrVWtq3Xwtw0GoYDE+OGqiEZz2kaVzd4bJOVbgQe5ofzgA5nbV2HsK3mwmmqvGkwLJhyAXn9bu9kMawy7nJZxb0dV//niO9U=
  app: mumu-mobile
  on:
    repo: niwasmala/mumu
