language: node_js
node_js:
- '0.10'
install:
- npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: OJxJ4qei7Wuc30He3G3GXem5oYlGS7IEdlFdZO2n+WQgVAS8BqiR0ULuYtQglX+V7NOovQ2zWvf3WGS11Zn5zHpsNJ4mZ6QvJPfqw9JqvJx6/4MSwXs4M+ZhNztcsGeYUve+aDxSTkPdp935GOh0lnFZvYYqKb2S1BPeNKi9jEQYwKICs06pOXbWL0rSIJXpP0dZ3heg46PfQEXBD5kudlDAHvYoXrV7fd74rQT9gh5JXsZdzs0GfMKgxI/abHfUH2vjmU+qJDiiMNPKmbqgJnSgPZjsifuxdXbOTJrtxTI899wxztOJvemo5NVvm9VYiwo/gnk1bCV/knPLT2hZH7cDGJ4wuG6NkNtQCVNIuEA0E0EmfMvRaRkg3NUKHDWNk4CNHKnaU9awYvoPxRRDv6dFCKLFfs7cXu9opStTBmsUOy1KvBiPC9C83qdGubRWL9zHqeBnOly09B21EEZsnRRbKUl+as6OlkVZnq4REjjCkKqCXLs/al6GGTmv5F0Xb1zab6x4h3noMBAGm3+RBbA7y58WUT3tuoJRihBE4spdwGKCuLw1q1s466Ev8jVcGjT2iEhdneCorH09p9X8YHV39SRoLElRVEpIBtTbcWm+LeJyHDgwDbqQ6DMl3jbfe0RpDgwmSghpgI8BnO+NZ3Y8J3UtjIe+O9NCb5DVh4U=
  app: arkavidia
  on:
    repo: niwasmala/dove-mail
